consumes:
  - application/json
info:

  description: A microservice for managing AWS cognito user accounts
  title: User Accounts Service
  version: 0.1.0
produces:
  - application/json
schemes:
  - http
swagger: "2.0"

