# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class NewThresholdPost(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, experiment: object=None):  # noqa: E501
        """NewThresholdPost - a model defined in Swagger

        :param experiment: The experiment of this NewThresholdPost.  # noqa: E501
        :type experiment: object
        """
        self.swagger_types = {
            'experiment': object
        }

        self.attribute_map = {
            'experiment': 'experiment'
        }

        self._experiment = experiment

    @classmethod
    def from_dict(cls, dikt) -> 'NewThresholdPost':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The newThresholdPost of this NewThresholdPost.  # noqa: E501
        :rtype: NewThresholdPost
        """
        return util.deserialize_model(dikt, cls)

    @property
    def experiment(self) -> object:
        """Gets the experiment of this NewThresholdPost.


        :return: The experiment of this NewThresholdPost.
        :rtype: object
        """
        return self._experiment

    @experiment.setter
    def experiment(self, experiment: object):
        """Sets the experiment of this NewThresholdPost.


        :param experiment: The experiment of this NewThresholdPost.
        :type experiment: object
        """
        if experiment is None:
            raise ValueError("Invalid value for `experiment`, must not be `None`")  # noqa: E501

        self._experiment = experiment
