
from swagger_server.models.existing_correlation_experiment import ExistingCorrelationExperiment
from swagger_server.models.existing_threshold_experiment import ExistingThresholdExperiment
from swagger_server.database_models.CorrelationExperiment import CorrelationExperiment
from swagger_server.database_models.ThresholdExperiment import ThresholdExperiment


def convertDbThresholdExperimentToSwaggerExperiment(dbModel:ThresholdExperiment):
    return ExistingThresholdExperiment(dbModel.experiment_id, dbModel.indicator, dbModel.ticker, dbModel.threshold)

def convertDbCorrelationExperimentToSwaggerExperiment(dbModel:CorrelationExperiment):
    return ExistingCorrelationExperiment(dbModel.experiment_id, dbModel.asset_1, dbModel.asset_2, dbModel.correlation, dbModel.asset_1_deltas, dbModel.asset_2_deltas)